[tool.poetry]
name = "undercooked-build"
version = "0.1.0"
description = ""
authors = ["Quint Guvernator <quint@guvernator.net>"]

[tool.poetry.dependencies]
python = "^3.9"
jinja2 = "^2.11.2"

#[build-system]
#requires = ["poetry>=0.12"]
#build-backend = "poetry.masonry.api"
